import vscode = require('vscode');
import beautify from 'js-beautify';

export async function startOpenSource(source: string, id: string) {
  const formattedJS = beautify.js(source, {
    indent_size: 2,
    space_in_empty_paren: true,
  });

  const header = `// BetterDiscord Module Source\n// Generated by BD Companion \n// Module ID: ${id}\n\n`;
  // if someone can format this better- please do so, thanks.

  const uri = vscode.Uri.parse(`untitled:${id}.js`);
  const doc = await vscode.workspace.openTextDocument(uri);
  const edit = new vscode.WorkspaceEdit();
  edit.insert(uri, new vscode.Position(0, 0), header + formattedJS);
  await vscode.workspace.applyEdit(edit);
  await vscode.window.showTextDocument(doc);
  // await vscode.commands.executeCommand('editor.action.formatDocument');
  // its done before its even given to the user- so its pointless
}
